# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: install json2yml
        run: |
          sudo npm install -g json2yaml
        
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test.json
      - id: set-matrix
        run: |
          JSON=$(cat ./test.json)
          j2=$(cat ./test.json | jq -c .)
          j3=${j2//'"'/'\"'}
          echo $JSON
          echo $j2
          echo $j3
          
          echo "hello from here"
          echo "::set-output name=matrix::$( echo "$j3" )
          
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Check matrix definition
        run: |
          matrix='$(( needs.matrix.outputs.matrix ))'
          echo "outputting raw value"
          echo $matrix
          echo "outputting pretty version"
          echo $matrix | jq
          echo "outputting yaml"
          echo $matrix | json2yaml
  backend:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps: 
      - name: hi
        run: |
          echo "hello"
