# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      
      - name: install json2yml
        run: |
          sudo npm install -g json2yaml
        
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test.json
      - name: read json
        run: |
          json='${{ steps.package.outputs.content }}'
          echo "outputting json version"
          echo $json | jq .
          echo "outputting j
          echo $json | json2yaml
          echo "set matrix"
         # matrix: ${{fromJSON(json)}}
         # echo "print out matrix"
         # echo $matrix     
      - id: set-matrix
        run: |
          matrix='${{ steps.package.outputs.content }}'
          #matrix=$((
          #  echo '{ "package" : ['
          #  sed -n "/^REVDEP *:= */ { s///; p }" revdep-dev/Makefile | sed 's/ /, /g' | xargs -n 1 echo | sed -r 's/^([^,]*)(,?)$/"\1"\2/'
          #  echo " ]}"
          #) | jq -c .)
          #echo $matrix
          #echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"
  backend:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps: 
      - name: hi
        run: |
          echo "hello"
