# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GetFormattedJson:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          j2=$(cat ./real.json | jq -c .)
          j3=${j2//'"'/'\"'}
          echo $j3
          echo "::set-output name=matrix::$( echo "$j3" )"
          
  check-matrix:
    runs-on: ubuntu-latest
    needs: GetFormattedJson
    outputs:
      matrix: ${{ steps.set-matrix.outputs.yaml }}
    steps:
      - name: install json2yaml
        run: |
          sudo npm install -g json2yaml
        
      - name: Check matrix definition
        run: |
          matrix="${{ needs.GetFormattedJson.outputs.matrix }}"
          echo "outputting raw value"
          echo $matrix
          echo "outputting pretty version"
          echo $matrix | jq

      - id: set-yaml
        run: |
          matrix="${{ needs.GetFormattedJson.outputs.matrix }}"
          yaml= $matrix | json2yaml
          echo "outputting yml"
          echo $yaml
  backend:
    runs-on: ubuntu-latest
    needs: check-matrix
    strategy:
      #fail-fast: false
      matrix: ${{needs.check-matrix.outputs.yaml}}
    steps: 
      - name: hi
        run: |
          echo "hello"
          echo ${{ matrix.package }}
        
