# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      
      - name: install json2yml
        run: |
          sudo npm install -g json2yaml
        
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./test.json
      - id: set-matrix
        run: |
          json='${{ steps.package.outputs.content }}'
          echo "outputting json single line version"
          echo $json | jq -c
          echo "outputting yaml"
          echo $json | json2yaml
          echo 
          echo "set matrix"
          matrix='${{ steps.package.outputs.content}}' | jq -c
          echo "::set-output name=matrix::$matrix"
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml
      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq -c .
          echo $matrix | json2yaml
          echo 
  backend:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps: 
      - name: hi
        run: |
          echo "hello"
